### ISSUE TITLE
Fix copy'n'paste error in front_insert_iterator

### ISSUE THREAD

**Issue by siebenschlaefer** [tcbrindle/NanoRange#103]
https://github.com/tcbrindle/NanoRange/blob/275a8088ae5a7bb409a2ef9c60e9df5f3fae3c72/include/nanorange/iterator/front_insert_iterator.hpp#L33

This looks like a copy & paste error where back_insert_iterator.hpp was copied and `push_back()` was mistakenly changed to `front_back` instead of `push_front` like in line 27:

https://github.com/tcbrindle/NanoRange/blob/275a8088ae5a7bb409a2ef9c60e9df5f3fae3c72/include/nanorange/iterator/front_insert_iterator.hpp#L27

Disclaimer: I just started toying with NanoRange, so the code may be totally fine. In that case just close this issue, sorry. Also, I didn't find any tests for the insert iterators, so I couldn't add a test case.

**Comment by tcbrindle** [comment]
That is definitely a copy-and-paste error, well spotted!

**Comment by tcbrindle** [comment]
Fixed in #104
