### ISSUE TITLE
Support better CMake install for to use with modern CMake.

### ISSUE THREAD

**Issue by FunMiles** [tcbrindle/NanoRange#112]
I just tried this library. It fits my purpose over range-v3 because Eric refuses to support the Intel compiler and I need to support it.
I decided to install it using conan.
The trouble, minor in the grand scheme of things, but nagging nonetheless, is that one cannot simply use:
```CMake
find_package(nanorange REQUIRED)
target_link_libraries(executable nanorange)
```
Instead I had to use
```CMake
include_directories(${nanorange_INCLUDE_DIRS})
```
This approach, though it works for my immediate purpose, is not appropriate for libraries that will be used by other targets in other projects.

I have not fully mastered the latest version of conan, but I have made some install scripts that rely on CMake install configurations that also installs the config version of '.cmake' files. When that is done properly then using
```CMake
find_package(nanorange REQUIRED NO_MODULES)
target_link_libraries(executable nanorange)
```
with or without conan will do the job.
One good thing is that the conan python file of nanorange relies on the cmake install, so the only modifications required should be in the install configuration inside of `CMakeLists.txt`
If I can help, I think it shouldn't take me too long to create a PR for this, based on some of my own libraries.

**Comment by tcbrindle** [comment]
I don't have any experience with Conan myself (support in NanoRange was contributed by @dvirtz) but I'm happy to accept PRs to improve the experience if it's currently suboptimal.

(I'm also pleased to hear that NanoRange works with ICC!)

**Comment by dvirtz** [comment]
While you're at it, I recommend also moving the recipe to https://github.com/conan-io/conan-center-index  as the current repo, bintray, is  [shutting down](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

**Comment by FunMiles** [comment]
@dvirtz I just had a bit of time to start looking at this. I see that in your commit for install, the install is actually almost complete to create the config files. I had to add a line to have the install paths properly defined.
However, I am hitting an old foe... It's the source of the `INTERFACE` library. Here's the error for a trimmed down version where I commented all but one include file after line 35.
```
michel@Michels-MacBook-Pro NanoBuild % cmake -DBUILD_TESTING=OFF -DUSE_SINGLE_HEADER=OFF -DDO_INSTALL=ON -DCMAKE_INSTALL_PREFIX=~/local/nanorange ../NanoRange
lib/cmake/nanorange vs lib
-- Configuring done
CMake Error in CMakeLists.txt:
  Target "nanorange" INTERFACE_SOURCES property contains path:

    "/Users/michel/Development/OpenSource/NanoRange/include/nanorange.hpp"

  which is prefixed in the source directory.


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```
This is a headache of CMake. I am not finding yet the best solution for this.
It seems that one is not supposed to list files the way they are now. I presume they are listed for an IDE?
I use CLion and having the include files listed used to be necessary for the the IDE to include a .h in the list of files it analyzes.  However nowadays, including the file in a listed .cpp file is enough.
The other way to get things to work is to list each file twice, under `$<INSTALL_INTERFACE:include>` and `$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>`.
I am a bit afraid that I am going to create a bigger than wished PR for this.

**Comment by dvirtz** [comment]
Is there a reason you disable USE_SINGLE_HEADER? The conan package turns it on: https://github.com/tcbrindle/NanoRange/blob/bf32251d65673fe170d602777c087786c529ead8/conanfile.py#L24

Actually, contrary to the original claim, the current conan package does support a target based consume, in fact this is how the conan test package has it: https://github.com/tcbrindle/NanoRange/blob/bf32251d65673fe170d602777c087786c529ead8/.conan/test_package/CMakeLists.txt#L7-L10

**Comment by FunMiles** [comment]
~~I'm embarrassed. It does work. I had looked into the file conan had created and not found the `nanorange::nanorange`.~~

On your question on the reason I disabled `USE_SINGLE_HEADER`, I noticed the single header is in there if you disable it. You get the multiple components. But you can still `#include <nanorange.hpp>` and get everything. If I left it enabled, it didn't allow me to include just some views for example.
Finally as I've mentioned, the source files being listed as they are, causes many warnings with CMake 3.19. And the tests give errors. So maybe that needs to be addressed instead? I'm closing this.

**Comment by FunMiles** [comment]
Update: Sorry. It seemed to work when I tried your lines of code, but only because cmake found my install and not conan's. 

With a straight conan install based on  `nanorange/20200505`, it does not work. The install via conan seems to go without problem but it never creates the cmake configuration files.

Maybe you have the same situation on your machine? Can you check from a fresh install not having any `CMAKE_PREFIX_PATH` or `CMAKE_MODULE_PATH` defined.
Perhaps it works with CMake pre 3.XX? I am using 3.18 and 3.19.

**Comment by FunMiles** [comment]
Update: Sorry. It seemed to work when I tried your lines of code, but only because cmake found my install and not conan's.

With a straight conan install based on nanorange/20200505, it does not work. The install via conan seems to go without problem but it never creates the cmake configuration files.

Maybe you have the same situation on your machine? Can you check from a fresh install not having any CMAKE_PREFIX_PATH or CMAKE_MODULE_PATH defined.
Perhaps it works with CMake pre 3.XX? I am using 3.18 and 3.19.


Here is a log of conan install and cmake:
```bash
conan install /Users/michel/Development/Tests/NanoConan -if=/Users/michel/Development/Tests/NanoConan/cmake-build-debug -pr=default
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=apple-clang
compiler.libcxx=libc++
compiler.version=12.0
os=Macos
os_build=Macos
[options]
[build_requires]
[env]

conanfile.py: Installing package
Requirements
Packages

Installing (downloading, building) binaries...
conanfile.py: Generator txt created conanbuildinfo.txt
conanfile.py: Generator cmake created conanbuildinfo.cmake
conanfile.py: Generated conaninfo.txt
conanfile.py: Generated graphinfo
"/Applications/CLion 2021.1 EAP.app/Contents/bin/cmake/mac/bin/cmake" -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" /Users/michel/Development/Tests/NanoConan
-- Conan: Adjusting output directories
-- Conan: Using cmake targets configuration
-- Conan: Adjusting default RPATHs Conan policies
-- Conan: Adjusting language standard
-- Current conanbuildinfo.cmake directory: /Users/michel/Development/Tests/NanoConan/cmake-build-debug
CMake Error at CMakeLists.txt:8 (find_package):
  Could not find a package configuration file provided by "nanorange" with
  any of the following names:

    nanorangeConfig.cmake
    nanorange-config.cmake

  Add the installation prefix of "nanorange" to CMAKE_PREFIX_PATH or set
  "nanorange_DIR" to a directory containing one of the above files.  If
  "nanorange" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/Users/michel/Development/Tests/NanoConan/cmake-build-debug/CMakeFiles/CMakeOutput.log".
See also "/Users/michel/Development/Tests/NanoConan/cmake-build-debug/CMakeFiles/CMakeError.log".

```
Looking in `~/.conan/data/nanorange`, there is not a single `.cmake` file generated.

**Comment by dvirtz** [comment]
Ok, I see that there's a recipe in [conan-center](https://github.com/conan-io/conan-center-index/blob/master/recipes/nanorange/all/conanfile.py) written by @FranckRJ.
You should open an issue there I believe.

**Comment by FranckRJ** [comment]
What's your cmake / conan configuration exactly ?

If you're using the cmake_find_package generator it's normal that there is
no "config" cmake file because it use FindXXX.cmake, this file should be
generated inside your install directory, not inside the conan package.

**Comment by FunMiles** [comment]
@FranckRJ I tried both with or without the cmake_find_package generator. Without cmake_find_package (see my conanfile.txt below), find_package fails. With cmake_find_package generator, find_package works but it does not create the desired target.
For reference here is my conanfile.txt:
```
[requires]
nanorange/20200505
[generators]
cmake_paths
cmake
```
And here is my CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.15)
project(nanotest VERSION 0.1.0)

set(CMAKE_CXX_STANDARD 17)

if(EXISTS ${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
    include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
    set(CMAKE_MODULE_PATH ${CMAKE_BINARY_DIR} ${CMAKE_MODULE_PATH})
    conan_basic_setup(TARGETS)
else()
    message(WARNING "The file conanbuildinfo.cmake doesn't exist, you have to run conan install first")
endif()

find_package(nanorange REQUIRED NO_MODULE)
add_executable(nano test.cpp)

target_link_libraries(nano nanorange::nanorange)
```
The `NO_MODULE` is useful when the cmake_find_package is turned on for some other libraries that do not create config files. With the `NO_MODULE`, the FIndXXX.cmake will not be considered. This is a reason for which a formula should ALWAYS create the config files in its CMake install phase, I think.

Note that using the original conan recipe and modifying the CMakeLists to address the issue with CMake v>3.0, I do get the config file generated where they should be.

**Comment by FranckRJ** [comment]
Conan-center explicitly forbid cmake config files. Packages must be
build-system agnostic.

https://github.com/conan-io/conan-center-index/blob/master/docs/error_knowledge_base.md#kb-h016-cmake-modules-config-files

So just remove the NO_MODULE and it will works, or use a different
generator if you don't like how cmake_find_package works (but it's the
recommended one for cmake).

**Comment by FunMiles** [comment]
@FranckRJ Until today the target nanorange::nanorange was not getting defined. Now it seems it is. 
I wonder if CMake was finding something else than the conan package. I'll close this as it is now working with cmake_find_package and removing the NO_MODULE.

**Comment by tcbrindle** [comment]
Just as a drive-by comment, the single-header version of NanoRange mostly exists for the convenience of people who *aren't* using package managers, so they can just drop one file into their project. Using the original headers in the `include/` directory would be better, as it allows you use more specific includes (e.g. `#include <nanorange/algorithm/transform.hpp>`) for faster compilation.

(But as I said, I don't know anything about Conan so I'll leave it to the people who do :-) )
