### ISSUE TITLE
implement view::concat?

### ISSUE THREAD

**Issue by ubsan** [tcbrindle/NanoRange#19]
I don't think it's in the ranges TS, but it's in ranges-v3, and I have an implementation if you'd like it.

(Note: concat is a terribly unintuitive name, if at all possible I would rename it to `chain` - this is what it's called in both Rust and D)

**Comment by tcbrindle** [comment]
Many of the views from Range-V3 would be tempting to add as extensions (`view::zip` a is particularly useful one), but at the moment I'd prefer to keep NanoRange in line with the ranges proposals. If you can persuade Eric and Casey to add `view::concat` then I'll gladly put it on the list for NanoRange.

As to the name, changing it might not be totally out of the question: Range-V3's `remove_if` was renamed (back) to `filter` for P0789. Again, you'd have to convince Eric and Casey (or eventually LEWG) though.

**Comment by ubsan** [comment]
@tcbrindle alright, sounds good! I'll see if it can get added in C++23, I don't want to change it for 20.
