### ISSUE TITLE
common_reference broken with MSVC 19.22

### ISSUE THREAD

**Issue by tcbrindle** [tcbrindle/NanoRange#75]
The latest MSVC update (v19.22) breaks our implementation of `common_reference`, to the extent that just `#include <nanorange.hpp>` generates

    error C2064: term does not evaluate to a function taking 0 arguments
    note: see reference to alias template instantiation 'nano::ranges::detail::cond_res_t<copy_cv<X,Y>::type&,copy_cv<Y,X>::type&>' being compiled

(See https://godbolt.org/z/VXv5gY)

The offending line seems to be https://github.com/tcbrindle/NanoRange/blob/master/include/nanorange/detail/common_reference.hpp#L68. I'm not sure of the cause -- this should be in a SFINAE context, so if evaluation of the alias causes a substitution failure, then the partial specialisation should just be ignored... or at least that's the idea.

It works correctly with Clang, GCC and previous versions of MSVC, so it may just be a compiler bug, or it may be that MSVC is now correctly diagnosing a problem that we previously got away with. Either way, this prevents NanoRange being used with the latest Windows compiler, so it needs to be fixed ASAP.

**Comment by PeterFeicht** [comment]
I think I ran into this at work, you wouldn't happen to have a reduced sample that triggers this? Or even filed a bug with MS?

**Comment by tcbrindle** [comment]
I do indeed:

https://developercommunity.visualstudio.com/content/problem/745820/alias-template-in-class-template-partial-specialis.html
