### ISSUE TITLE
nano::to_vector ?

### ISSUE THREAD

**Issue by Guekka** [tcbrindle/NanoRange#91]
Sorry if it is obvious, but I did not find a way to convert a range to a vector.
Simple example: 
``std::vector<int> = nano::views::iota(0, 1000); // | nano::to_vector ?``

``//In Range-v3``
``return ranges::views::iota(0, starterSize) | ranges::to_vector;``

So, is it possible? Thanks

**Comment by tcbrindle** [comment]
There is no `std::ranges::to_vector` in C++20, so there isn't one in NanoRange :)

This should work though?

```cpp
template <typename T, typename Rng>
std::vector<T> to_vector(Rng&& rng)
{
    auto v = nano::views::common(std::forward<Rng>(rng));
    return std::vector<T>(v.begin(), v.end());
}

template <typename T>
auto to_vector()
{
    return nano::detail::rao_proxy{[](auto&& rng) { 
        return ::to_vector<T>(std::forward<decltype(rng)>(rng));
    }};
}
```

https://godbolt.org/z/oFe8Lx

**Comment by Guekka** [comment]
Having to specify explicitly the type of the vector is not very convenient. But thank you for this quick answer, this will work perfectly

**Comment by tcbrindle** [comment]
There is indeed a `nano::range_value_t` alias template which you can use to get a range's value type, but using that as the default template argument gets tricky.

An alternative is to use CTAD, for example:

```cpp
template <typename T = void, typename Rng>
auto to_vector(Rng&& rng)
{
    auto v = nano::views::common(std::forward<Rng>(rng));

    if constexpr (nano::same_as<T, void>) {
        return std::vector(v.begin(), v.end());
    } else {
        return std::vector<T>(v.begin(), v.end());
    }
}

template <typename T = void>
auto to_vector()
{
    if constexpr (nano::same_as<T, void>) {
        return nano::detail::rao_proxy([](auto&& rng) {
            return ::to_vector(std::forward<decltype(rng)>(rng));
        });
    } else {
        return nano::detail::rao_proxy{[](auto&& rng) { 
           return ::to_vector<T>(std::forward<decltype(rng)>(rng));
        }};
    }
}

int main()
{
    // Using explicit type
    auto vec1 = nano::views::iota(1, 10) | to_vector<int>();

    // Using CTAD
    auto vec2 = nano::views::iota(1, 10) | to_vector();
}
```

https://godbolt.org/z/ssXWYv

**Comment by Guekka** [comment]
This is exactly what I was looking for, thank you! 
Maybe you could write that somewhere, it might be useful for someone else?
I'm closing the issue anyway, thanks again.
